### ISSUE TITLE
Really important bug to solve

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-help#3]
I'm from Brazil and really like Deepin, but we have 2 mirrors in Brazil, but both fail.

Best mirror server in Brazil is this: http://linuxdeepin.c3sl.ufpr.br
But is obsolete, don't show unstable repository, i'm make contact to ufpr.br, but they say need contact from Deepin Team telling corect rsync command for update repository.

Please send mail to carlos@fisica.ufpr.br for solve this problem.

Another mirror in Brazil is: http://sft.if.usp.br/deepin
This mirror is updated, but show this error on installing package: Hash Sum incorrect

Lot another mirrors in another countries have obsolete packages, please, contact they for solve this.

I'm contact Deepin in forum and bugzilla, but don't have response, sorry for send this in github, but for me and lot people in my country need this for good use of Deepin.

**Comment by hualet** [comment]
Hi bigbruno
Sorry for the trouble, this page  https://www.deepin.org/mirror.html#provide provides information on how to provide a mirror for deepin. We'll try to make contact with the mirror providers as soon as possible. 
Thanks.

**Comment by bigbruno** [comment]
Thanks for attention.

**Comment by deepinzhangshuang** [comment]
I tested  http://sft.if.usp.br/deepin  ,and it's ok  to update.  for deb http://http://sft.if.usp.br/deepin unstable main non-free contrib
获取:14 http://sft.if.usp.br/deepin unstable InRelease [13.8 kB]  
获取:15 http://sft.if.usp.br/deepin unstable/main amd64 Packages [16.2 MB]
获取:16 http://sft.if.usp.br/deepin unstable/main i386 Packages [16.1 MB]  
获取:17 http://sft.if.usp.br/deepin unstable/main amd64 Contents (deb) [28.9 MB]  
获取:18 http://sft.if.usp.br/deepin unstable/main i386 Contents (deb) [29.1 MB]  
获取:19 http://sft.if.usp.br/deepin unstable/contrib amd64 Packages [156 kB]  
获取:20 http://sft.if.usp.br/deepin unstable/contrib i386 Packages [156 kB]  
获取:21 http://sft.if.usp.br/deepin unstable/contrib amd64 Contents (deb) [250 kB]  
获取:22 http://sft.if.usp.br/deepin unstable/contrib i386 Contents (deb) [251 kB]  
获取:23 http://sft.if.usp.br/deepin unstable/non-free amd64 Packages [241 kB]  
获取:24 http://sft.if.usp.br/deepin unstable/non-free i386 Packages [232 kB]  
获取:25 http://sft.if.usp.br/deepin unstable/non-free amd64 Contents (deb) [1,165 kB]  
获取:26 http://sft.if.usp.br/deepin unstable/non-free i386 Contents (deb) [1,163 kB]  
已下载 94.0 MB，耗时 15分 9秒 (103 kB/s)  
正在读取软件包列表... 完成

**Comment by bigbruno** [comment]
deepinzhangshuang,  this mirror "http://sft.if.usp.br/deepin" is ok to apt-get update, but fail with use apt-get install, after complete download show error in Hash sum.

**Comment by deepinzhangshuang** [comment]
I tested install dde=15.3+3 , and it's ok . maybe you can give me a package list to test

**Comment by bigbruno** [comment]
I'm try thunderbird and gtk-gnutella, both fail, but in another days i'm try lot of packages and lot fails.

sudo apt-get install gtk-gnutella
Need to get 15.5 MB of archives.
After this operation, 32.4 MB of additional disk space will be used.
Get:1 http://sft.if.usp.br/deepin unstable/main amd64 gtk-gnutella amd64 1.1.8-1+b1 [15.5 MB]
Err:1 http://sft.if.usp.br/deepin unstable/main amd64 gtk-gnutella amd64 1.1.8-1+b1  
  Hash Sum mismatch
Fetched 15.5 MB in 11s (1316 kB/s)  
E: Failed to fetch http://sft.if.usp.br/deepin/pool/main/g/gtk-gnutella/gtk-gnutella_1.1.8-1+b1_amd64.deb  Hash Sum mismatch

sudo apt-get install thunderbird
Need to get 32.9 MB of archives.
After this operation, 90.7 MB of additional disk space will be used.
Get:1 http://sft.if.usp.br/deepin unstable/main amd64 thunderbird amd64 1:38.3.0+build1-0ubuntu0.14.04.1 [32.9 MB]
Err:1 http://sft.if.usp.br/deepin unstable/main amd64 thunderbird amd64 1:38.3.0+build1-0ubuntu0.14.04.1  
  Hash Sum mismatch
Fetched 32.9 MB in 21s (1496 kB/s)  
E: Failed to fetch http://sft.if.usp.br/deepin/pool/main/t/thunderbird/thunderbird_38.3.0+build1-0ubuntu0.14.04.1_amd64.deb  Hash Sum mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by snyh** [comment]
@bigbruno  Do you have try download the deb by wget directly and compare the md5sum with `apt-get show thunderbird` 

ps:
It has a rarely case cause apt-get report hash sum mismatch if the wrong deb already in /var/cache/apt/archives. (in this case you must delete the wrong deb manually)

**Comment by bigbruno** [comment]
Hi, i'm back.

All repositories i'm tested to update deepin 15.2 to deepin 15.3 not work, except the primary mirror.

http://packages.deepin.com/deepin/ - Show packages for update, and apt-get upgrade is fine.

http://linuxdeepin.c3sl.ufpr.br
http://deepin.mirror.gtcomm.net
http://sft.if.usp.br/deepin/

In this 3 mirrors, i'm find packages updated searching manually in folders, but after use apt-get update, apt-get only show old packages, not show any package released in deepin 15.3.

For example, this folder have deepin terminal 2.0.14, but in apt-get only find 1.1.7 version: http://linuxdeepin.c3sl.ufpr.br/deepin/pool/main/d/deepin-terminal/

In Brazil oficial mirror is very slow, like 15 kb/s, that is why we really need fine mirrors.

**Comment by bigbruno** [comment]
I'm tested another mirror and this bug is generality: http://ftp.nluug.nl/os/Linux/distr/deepin/

New packages present in repository, but not show in apt-get. Apt-get only found old packages.

**Comment by bigbruno** [comment]
Packages files in http://cdn.packages.deepin.com/ they are obsolete.

For example: http://cdn.packages.deepin.com/deepin/dists/unstable/main/binary-amd64/Packages.gz - Date from: 07-Sep-2016 11:26

But in oficial mirror: http://packages.deepin.com/deepin/dists/unstable/main/binary-amd64/Packages.gz - Date from: 12-Sep-2016 05:46

That's make  all mirrors off Deepin obsolete.

**Comment by rafaeldev** [comment]
Some more information on this topic?
I'm try now install `mysql-server` from **http://sft.if.usp.br/deepin/** but i had the same problem with Hashes verifications...

My source.list file content:
```
## Generated by deepin-installer
# deb [by-hash=force] http://packages.deepin.com/deepin panda main contrib non-free
# deb-src http://packages.deepin.com/deepin panda main contrib non-free
deb [by-hash=force] http://sft.if.usp.br/deepin/ panda main contrib non-free
```

Thanks!

**Comment by snyh** [comment]
@rafaeldev  is this problem persist ?  
You have manually changed the source.list to sft.if.usp.br, so there hasn't any feature added by deepin. It maybe a network transition problem occasionally.

**Comment by rafaeldev** [comment]
It's happens still.
The source `sft.if.usp.br` is not up to date with main repo.

I "fix" this adding others repos on source list:

```bash
## Generated by deepin-installer

# deb-src http://packages.deepin.com/deepin panda main contrib non-free

deb [by-hash=force] http://sft.if.usp.br/deepin/ panda main contrib non-free
deb [by-hash=force] http://linuxdeepin.c3sl.ufpr.br/deepin/ unstable main contrib non-free
deb [by-hash=force] http://packages.deepin.com/deepin panda main contrib non-free
```

**Comment by snyh** [comment]
the bottom of page https://ci.deepin.io/job/mirror_status/931/console has the sync status of all mirrors.  (you need 

@rafaeldev  You can check this next if the problem occurs.

**Comment by jair-anderson-souza** [comment]
Thanks @bigbruno for the answer, and thank to @rafaeldev, these mirrors worked for me.

**Comment by BLumia** [comment]
FYI for new comer you may need to change the `panda` in the mirror content to `lion` since the new deepin stable software repository is not the same as the old one :)
