### ISSUE TITLE
Really important bug to solve - part II

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-help#4]
Almost all the mirrors out of China point to the CDN, but the CDN itself is not updating correctly, today we have other countries not in the repositories for updates Deepin 15.3.

Again I come to report to github as email, bugtracker and forum did not get answers for a week.

Please check this folder http://cdn.packages.deepin.com/deepin/dists/unstable/
Files date by 07 sep.

But in http://packages.deepin.com/deepin/dists/unstable/main/
Files date by 12 sep.

Some files date by day 07, but in China repository released update in day 12.

**Comment by arraisfilho** [comment]
This problem reported by @bigbruno  is something that greatly affects updates and download packages. I have noticed that this problem occurs constantly.

Checking other mirros the Deepin, we note that almost all are outdated.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
